sudo: required
language: scala
scala:
- 2.11.11
services:
- docker
notifications:
  email: false
install: true
before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_d44bf3a7d844_key -iv $encrypted_d44bf3a7d844_iv -in tests/credentials.json.enc -out tests/credentials.json -d; fi'
- "./tools/travis/setup.sh"
script:
- "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/deploy_push.sh && ./tools/travis/test.sh"
